const supportedLanguages = [
  ["auto", "auto"],
  ["zh-Hans", "zh-CN"],
  ["zh-Hant", "zh-TW"],
  ["en", "en"],
  ["en", "en"],
  ["ja", "ja"],
  ["ko", "ko"],
  ["fr", "fr"],
  ["de", "de"],
  ["es", "es"],
  ["it", "it"],
  ["ru", "ru"],
  ["pt", "pt"],
  ["nl", "nl"],
  ["pl", "pl"],
  ["ar", "ar"],
  ["af", "af"],
  ["am", "am"],
  ["az", "az"],
  ["be", "be"],
  ["bg", "bg"],
  ["bn", "bn"],
  ["bs", "bs"],
  ["ca", "ca"],
  ["ceb", "ceb"],
  ["co", "co"],
  ["cs", "cs"],
  ["cy", "cy"],
  ["da", "da"],
  ["el", "el"],
  ["eo", "eo"],
  ["et", "et"],
  ["eu", "eu"],
  ["fa", "fa"],
  ["fi", "fi"],
  ["fj", "fj"],
  ["fy", "fy"],
  ["ga", "ga"],
  ["gd", "gd"],
  ["gl", "gl"],
  ["gu", "gu"],
  ["ha", "ha"],
  ["haw", "haw"],
  ["he", "he"],
  ["hi", "hi"],
  ["hmn", "hmn"],
  ["hr", "hr"],
  ["ht", "ht"],
  ["hu", "hu"],
  ["hy", "hy"],
  ["id", "id"],
  ["ig", "ig"],
  ["is", "is"],
  ["jw", "jw"],
  ["ka", "ka"],
  ["kk", "kk"],
  ["km", "km"],
  ["kn", "kn"],
  ["ku", "ku"],
  ["ky", "ky"],
  ["la", "lo"],
  ["lb", "lb"],
  ["lo", "lo"],
  ["lt", "lt"],
  ["lv", "lv"],
  ["mg", "mg"],
  ["mi", "mi"],
  ["mk", "mk"],
  ["ml", "ml"],
  ["mn", "mn"],
  ["mr", "mr"],
  ["ms", "ms"],
  ["mt", "mt"],
  ["my", "my"],
  ["ne", "ne"],
  ["no", "no"],
  ["ny", "ny"],
  ["or", "or"],
  ["pa", "pa"],
  ["ps", "ps"],
  ["ro", "ro"],
  ["rw", "rw"],
  ["si", "si"],
  ["sk", "sk"],
  ["sl", "sl"],
  ["sm", "sm"],
  ["sn", "sn"],
  ["so", "so"],
  ["sq", "sq"],
  ["sr", "sr"],
  ["sr-Cyrl", "sr"],
  ["sr-Latn", "sr"],
  ["st", "st"],
  ["su", "su"],
  ["sv", "sv"],
  ["sw", "sw"],
  ["ta", "ta"],
  ["te", "te"],
  ["tg", "tg"],
  ["th", "th"],
  ["tk", "tk"],
  ["tl", "tl"],
  ["tr", "tr"],
  ["tt", "tt"],
  ["ug", "ug"],
  ["uk", "uk"],
  ["ur", "ur"],
  ["uz", "uz"],
  ["vi", "vi"],
  ["xh", "xh"],
  ["yi", "yi"],
  ["yo", "yo"],
  ["zu", "zu"],
];

const common = {
  "auto": ["any"],
  "zh": ["any"],
  "zh-hans": ["any"],
  "zh-hant": ["any"],
  "en": ["any"],
  "ja": ["zh", "zh-hant","en", "ko"],
  "ko": ["zh", "zh-hant","en", "ja"],
  "fr": ["any"],
  "es": ["any"],
  "it": ["any"],
  "de": ["any"],
  "tr": ["any"],
  "ru": ["any"],
  "pt": ["any"],
  "vi": ["any"],
  "id": ["any"],
  "th": ["any"],
  "ms": ["any"],
  "ar": ["en"],
  "hi": ["en"]
}

const langMap = {
  auto: {
    "any": ["any"]
  },
  caiyun: {
    "en": ["zh-hans","zh","zh-hant"],
    "zh-hans": ["en","ja"],
    "zh": ["en","ja"],
    "zh-hant": ["en","ja"],
    "ja": ["zh-hans","zh","zh-hant"]
  },
  baidu: {
    "en": ["zh", "ja", "ko", "fr", "es", "it", "de", "ru", "pt", "vi", "ar"],
    "zh": ["en","ja","ko"],
    "zh-hans": ["en","ja","ko"],
    "zh-hant": ["en","ja","ko"],
    "ja": ["zh", "zh-hant","en", "ko"],
    "ko": ["zh", "zh-hant","en", "ja"],
    "fr": ["zh", "zh-hant","en", "es", "it", "de", "ru", "pt"],
    "es": ["zh", "zh-hant","en", "fr", "it", "de", "ru", "pt"],
    "it": ["zh", "zh-hant","en", "fr", "es", "de", "ru", "pt"],
    "de": ["zh", "zh-hant","en", "fr", "es", "it", "ru", "pt"]
  },
  tencent: {
    "auto": ["any"],
    "zh": ["en", "ja", "ko", "fr", "es", "it", "de", "tr", "ru", "pt", "vi", "id", "th", "ms"],
    "zh-hans": ["en", "ja", "ko", "fr", "es", "it", "de", "tr", "ru", "pt", "vi", "id", "th", "ms"],
    "zh-hant": ["en", "ja", "ko", "fr", "es", "it", "de", "tr", "ru", "pt", "vi", "id", "th", "ms"],
    "en": ["zh", "zh-hant","zh-hans","ja", "ko", "fr", "es", "it", "de", "tr", "ru", "pt", "vi", "id", "th", "ms", "ar", "hi"],
    "ja": ["zh", "zh-hant","zh-hans","en", "ko"],
    "ko": ["zh", "zh-hant","zh-hans","en", "ja"],
    "fr": ["zh", "zh-hant","zh-hans","en", "es", "it", "de", "tr", "ru", "pt"],
    "es": ["zh", "zh-hant","zh-hans","en", "fr", "it", "de", "tr", "ru", "pt"],
    "it": ["zh", "zh-hant","zh-hans","en", "fr", "es", "de", "tr", "ru", "pt"],
    "de": ["zh", "zh-hant","zh-hans","en", "fr", "es", "it", "tr", "ru", "pt"],
    "tr": ["zh", "zh-hant","zh-hans","en", "fr", "es", "it", "de", "ru", "pt"],
    "ru": ["zh", "zh-hant","zh-hans","en", "fr", "es", "it", "de", "tr", "pt"],
    "pt": ["zh", "zh-hant","zh-hans","en", "fr", "es", "it", "de", "tr", "ru"],
    "vi": ["zh", "zh-hant","zh-hans","en"],
    "id": ["zh", "zh-hant","zh-hans","en"],
    "th": ["zh", "zh-hant","zh-hans","en"],
    "ms": ["zh", "zh-hant","zh-hans","en"],
    "ar": ["en"],
    "hi": ["en"]
  },
  deeplx: common,
  googlex: common,
}

exports.supportedLanguages = supportedLanguages;
exports.langMap = langMap;
